openapi: '3.0.2'
info:
  title: Onboarding API 
  version: '1.0'
  description: STD22049
servers:
  - url: https://STD22049.com
tags:
  - name: Student
    description: Everything about student
  - name: Teacher
    description: Everything about teacher and the courses that they're teaching
paths:
  /student:
    get:
      tags:
        - Student
      summary: Display students
      description: get the list of the students
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Students'
        '500':
          description: invalid server error
    post:
      tags:
        - Student
      summary: add new student
      requestBody: 
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/Students'
      responses: 
        '201':
          description: added succesfully
          content: 
            application/json: 
              schema: 
                type: array
                $ref: '#/components/schemas/Students'
        '500':
          description: invalid server error
  /student/{id}:
    get:
      tags:
        - Student
      parameters:
        - name: id
          in: query
          description: specified id
          required: true
          schema:
            type: integer
      summary: Display student by id
      description: get one student using his id
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/Students'
        '500':
          description: invalid server error
    put:
      tags:
        - Student
      parameters:
        - name: id
          in: query
          description: specified id
          required: true
          schema:
            type: integer
      summary: Update a student
      description: Update the stdRef and the name
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatedStudent'
      responses:
        '200':
          description: updated succesfully
        '500':
          description: server error
    delete:
      tags:
        - Student
      parameters:
        - name: id
          in: query
          description: specified id
          required: true
          schema:
            type: integer
      summary: Delete a student
      description: Delete definitively a student using his id
      responses:
        '200':
          description: Deleted succesfully
        '404':
          description: Student not found
        '500': 
          description: server error
  /teachers:
    get:
      tags:
        - Teacher
      summary: Display teacher
      description: get the list of all teachers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Teachers'
        '500':
          description: invalid server error
    post:
      tags:
        - Teacher
      summary: Post a teacher
      description: Add new teacher with his attributes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Teachers'
      responses:
        '200':
          description: added succesfully
        '500':
          description: server error
components:
  schemas:
    Students:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Rakoto'
        birthDate:
          type: string
          format: date-time
          example: '2023-02-25 12:00:00'
        stdRef:
          type: string
          example: 'STD22011'
    Teachers:
      type: object
      properties:
        firstName:
          type: string
          example: 'Tokimahery'
        lastName:
          type: string
          example: 'Ramarozaka'
        courses:
          $ref: '#/components/schemas/Courses'
    UpdatedStudent:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Rabe'
        birthDate:
          type: string
          format: date-time
          example: '2023-02-25 12:00:00'
        stdRef:
          type: string
          example: 'STD22015'
          
    Courses:
      type: array
      items:
        type: string
      example: ['PROG2','WEB1','DONNEE1']
      enum:
              - 'PROG1'
              - 'WEB1'
              - 'SYS1'
              - 'MGT1'
              - 'DONNEE1'
              - 'API'
              - 'PROG2'
              - 'WEB2'
              - 'SYS2'
            
            

          

  
