openapi: '3.0.2'
info:
  title: Onboarding API 
  version: '1.0'
  description: STD22049
servers:
  - url: https://STD22049.com
tags:
  - name: Student
    description: Everything about student
  - name: Teacher
    description: Everything about teacher and the courses that they're teaching
paths:
  /student:
    get:
      tags:
        - Student
      summary: Display students
      description: get the list of the students
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/Students'
        '500':
          description: invalid server error
    post:
      tags:
        - Student
      summary: add new student
      requestBody: 
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/Students'
      responses: 
        '201':
          description: added succesfully
          content: 
            application/json: 
              schema: 
                type: array
                $ref: '#/components/schemas/Students'
        '500':
          description: invalid server error
components:
  schemas:
    Students:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Rakoto'
        birthDate:
          type: string
          format: date-time
          example: '2023-02-25 12:00:00'
        stdRef:
          type: string
          example: 'STD22011'

  
